### ISSUE TITLE
StationName order when using formatObservations

### ISSUE THREAD

**Issue by map579** [Weiming-Hu/AnalogsEnsemble#100]
When creating an observations list via the formatObservations function, the Station Names in the observations list output are not listed in ascending order.  In my data (attached), 10-digit integers represent unique ambient air quality monitoring stations.  When the observations list is created, three of the monitoring stations' IDs are out of order and included at the end of the list.  The associated Xs and Ys  coordinates in the last three positions are correct as they relate to the last three monitoring stations.  I have formatted the monitoring stations' IDs as characters and integers, and the same three are out of order after running format Observations.

I am using the exact script from the help file example for formatObservations.

Thanks! - Mark
[obs15to18Final.zip](https://github.com/Weiming-Hu/AnalogsEnsemble/files/4472151/obs15to18Final.zip)

**Comment by Weiming-Hu** [comment]
Mark, I took a look at the code and this is indeed the case: observations are sorted based on any riteria.

Since it is desirable to have them sorted, I added an argument in this commit 4272228e5dbccbcb9c89d4f4d4d4c789919e232d. Please update your package and try it out.

**Comment by map579** [comment]
Hi Weiming.  I've updated the package and tried it twice, but formatObservations still results in the same 3 stations appearing at the end of the list, out of order (whether I declare the station IDs as characters or integers).

**Comment by Weiming-Hu** [comment]
Did you set the argument `sort.stations`?

**Comment by map579** [comment]
Haha!  You snuck in a new argument. :)  

So I was missing the "s" on StationName**s**, as well.  After adding the new argument and fixing the name of the column, the function is working as expected.  I did some spot checks on the data and looks good.  Thanks!
