### ISSUE TITLE
RAnEn installation failed on Windows

### ISSUE THREAD

**Issue by stonemoonkey** [Weiming-Hu/AnalogsEnsemble#101]
**Describe the bug**
loading failed after compliling
**To Reproduce**

**Expected behavior**
during building there are numerous complains about BH package like '...BH/include/boost/mpl/assert.hpp:199:21: warning: unnecessary parentheses in declaration of 'assert_not_arg' [-Wparentheses]
 failed ************ (boost::mpl::not_<Pred>::************'
then during testing, error appeared
'building package indices
 testing if installed package can be loaded from temporary location
arch - i386
Error: package or namespace load failed for 'RAnEn' in namespaceExport(ns, exports):
 undefined exports: Config'

**Desktop (please complete the following information):**

R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Additional context**

**Comment by Weiming-Hu** [comment]
Did you try this out with the ungraded Rtools?

**Comment by Weiming-Hu** [comment]
Here is the error message from the installation process.

```
...
Rd warning: C:/Users/a/AppData/Local/Temp/RtmpmS0IzB/R.INSTALL7645388661/RAnEn/man/schaakeShuffle.Rd:10: missing link 'generateAnalogs.default'
    toForecastTime                          html  
Rd warning: C:/Users/a/AppData/Local/Temp/RtmpmS0IzB/R.INSTALL7645388661/RAnEn/man/toForecastTime.Rd:11: missing link 'generateAnalogs.default'
Rd warning: C:/Users/a/AppData/Local/Temp/RtmpmS0IzB/R.INSTALL7645388661/RAnEn/man/toForecastTime.Rd:32: missing link 'generateAnalogs.default'
    toMemberForecasts                       html  
    writeConfig                             html  
    writeNetCDF                             html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'RAnEn' in namespaceExport(ns, exports):
 undefined exports: Config
¥ÌŒÛ: ‘ÿ»Î ß∞‹
Õ£÷π÷¥––
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/a/Documents/R/win-library/3.6/RAnEn'
```

The user is using R version 3.6 but the Rtool version 4.0.

After downgrading Rtool, the package installs correclty.

**Comment by Weiming-Hu** [comment]
You need to make sure that your Rtools version works with your R version. Please pay attention to the red texts on [the Rtool page](https://cran.r-project.org/bin/windows/Rtools/).
