### ISSUE TITLE
Issue with swift and Xcode

### ISSUE THREAD

**Issue by SGPeckham** [Weiming-Hu/AnalogsEnsemble#105]
Installing RAnEn on Rstudio version 

The BH and Rcpp packages installed without issue.

Installing next the RAnEn package.  The following is the command at the ">" prompt and the reply.

> install.packages("https://github.com/Weiming-Hu/AnalogsEnsemble/raw/master/RAnalogs/releases/RAnEn_latest.tar.gz", repos = NULL)
trying URL 'https://github.com/Weiming-Hu/AnalogsEnsemble/raw/master/RAnalogs/releases/RAnEn_latest.tar.gz'
Content type 'application/octet-stream' length 113682 bytes (111 KB)
==================================================
downloaded 111 KB

* installing *source* package ‘RAnEn’ ...
** using staged installation
Checking whether R_HOME is already set? R_HOME = /Library/Frameworks/R.framework/Resources
objc[8891]: Class _TtCs18__stdlib_AtomicInt is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7fffafa600c8) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x105427158). One of the two will be used. Which one is undefined.
objc[8891]: Class _TtCs19__EmptyArrayStorage is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7fffafa521e0) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x105419268). One of the two will be used. Which one is undefined.
objc[8891]: Class _TtCVVs17__CocoaDictionary5Index7Storage is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7fffafa60258) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x1054272e8). One of the two will be used. Which one is undefined.
objc[8891]: Class _TtCVs17__CocoaDictionary8Iterator is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7fffafa60310) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x1054273a0). One of the two will be used. Which one is undefined.
objc[8891]: Class _TtCs22__RawDictionaryStorage is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7fffafa52290) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x105419318). One of the two will be used. Which one is undefined.
objc[8891]: Class _TtCs26__EmptyDictionarySingleton is implemented in both /usr/lib/swift/libsw...
...
...
...
objc[8948]: Class __SwiftNativeNSDataBase is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7fffafa52e48) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x11012bed0). One of the two will be used. Which one is undefined.
objc[8948]: Class __SwiftNativeNSIndexSetBase is implemented in both /usr/lib/swift/libswiftCore.dylib (0x7fffafa52e98) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x11012bf20). One of the two will be used. Which one is undefined.
This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.

make: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!

make: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
checking whether the C++ compiler works... no
configure: error: in `/private/var/folders/2f/pfcn2jx173vgdftdrthhtzbm9tsskm/T/Rtmp7FHuFE/R.INSTALL225563877ac9/RAnEn':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘RAnEn’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RAnEn’
Warning in install.packages :
  installation of package ‘/var/folders/2f/pfcn2jx173vgdftdrthhtzbm9tsskm/T//RtmpAvWRsq/downloaded_packages/RAnEn_latest.tar.gz’ had non-zero exit status

--------
Mac us running Mojave 10.14.6.

Also get the same results using the R-base interactive window.

**Comment by Weiming-Hu** [comment]
Aha. Mojave. Have you checked out [this issue](https://github.com/Weiming-Hu/AnalogsEnsemble/issues/13#issuecomment-447060535)? I guess you need to install xcode developer tools.

Basically, you need to:

1. Open Xcode and see whether you have any automatic updates showing up.
2. Run `xcode-select --install` in a terminal to check for developer tools
3. Run `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` to complete the developing environment according to [this](https://github.com/Weiming-Hu/AnalogsEnsemble/issues/13#issuecomment-447150577)

**Comment by SGPeckham** [comment]
I tried going down this path, but hit a couple of snags right off.

1. Xcode would only update to the latest version if I was running the latest OS.  Work requires that I not use the latest OS.  Can not use the latest version of Xcode.
2. Tried running this command and the computer replied that I had the latest version.

My solution was to delete Xcode and download the application from the developer's site.  After the reinstall the RAnEn package installed.

Problem:  The next package in tutorial exercise 1 is:RnAnExtra.  When running the exercise on my computer using Rstudio (now with HB, Rcpp and RAnEn packages installed) the code execution stops at the next package load.  The message is:

Error in library(RAnEnExtra) : there is no package called ‘RAnEnExtra’

I loaded RnAen package with the command

install.packages("https://github.com/Weiming-Hu/AnalogsEnsemble/raw/master/RAnalogs/releases/RAnEn_latest.tar.gz", repos = NULL)

Did a dependency get missed?

**Comment by Weiming-Hu** [comment]
Ooooops, you need this. I should have put this in the documentation. Thanks for the headsup.

`devtools::install_github("Weiming-Hu/RAnEnExtra")`

**Comment by SGPeckham** [comment]
Actually, since I have a new install fo Rstudio, one needs to install the devtools package.  

Then, after the devtools command is available, can one install the RAnEnExtra package.

**Comment by Weiming-Hu** [comment]
That sounds good.
