### ISSUE TITLE
Work with timeseries of observations and forecast

### ISSUE THREAD

**Issue by natsis** [Weiming-Hu/AnalogsEnsemble#108]
I am using RAnEn to correct forecast using observations.

I have a minimum example of my implementation that should run easily: https://github.com/natsis/RAnEn_application
I think I have structured the data correctly but still, I am missing something.

The scripts runs, but every time, I can get only one prediction per day and not the hourly values I expected.

**Comment by natsis** [comment]
I had an follow up answer, as I fist ask through email

```
I took a look at your script. Your observations turn out to be mostly NA. This is probably why your analogs are mostly NA. Do you know why your observations are mostly NA?

> length(observations$Data)
[1] 34632
> length(which(is.na(observations$Data)))
[1] 33270
```

**Comment by natsis** [comment]
Thanks to Weiming-Hu I solved the problem!
The reshaping of the data was not correct!

**Comment by Weiming-Hu** [comment]
Thank you for taking care of this.
