### ISSUE TITLE
Missing values found in RAnEn

### ISSUE THREAD

**Issue by mcalovi** [Weiming-Hu/AnalogsEnsemble#11]
Using RAnEn package and foud missing values in the results.
Here the data: 

```
data.dir  <- "~/geolab_storage_V3/data/ExtremeHeat/NYdata/"
gfs.fname <- "gfs_209_68.Rdata"
pws.fname <- "pws.Rdata"
```

Code to run (SVN repository: geolab/projects/ExtremeHeat) `AnEn_GFS_PWS.R`

I found NAs in the results:

```
AnEn$analogs[1, 256, 12, , ]
      [,1] [,2] [,3]
 [1,]  NaN  NaN  NaN
 [2,]  NaN  NaN  NaN
 [3,]  NaN  NaN  NaN
 [4,]  NaN  NaN  NaN
 [5,]  NaN  NaN  NaN
 [6,]  NaN  NaN  NaN
 [7,]  NaN  NaN  NaN
 [8,]  NaN  NaN  NaN
 [9,]  NaN  NaN  NaN
[10,]  NaN  NaN  NaN
[11,]  NaN  NaN  NaN
[12,]  NaN  NaN  NaN
[13,]  NaN  NaN  NaN
[14,]  NaN  NaN  NaN
[15,]  NaN  NaN  NaN
[16,]  NaN  NaN  NaN
[17,]  NaN  NaN  NaN
[18,]  NaN  NaN  NaN
[19,]  NaN  NaN  NaN
[20,]  NaN  NaN  NaN
[21,]  NaN  NaN  NaN
```

**Comment by Weiming-Hu** [comment]
Hi Martina. When I tried to run the script, I didn't have any NA results. Please look below output.

```
...
> AnEn = compute_analogs(forecasts = gfs$fct,
+                        observations = pws$obsna,
+                        forecasts.circulars,
+                        weights = weights,
+                        stations_ID = stations_ID,
+                        test_ID_start = test_ID[1],
+                        test_ID_end = test_ID[length(test_ID)],
+                        train_ID_start = train_ID[1],
+                        train_ID_end = train_ID[length(train_ID)],
+                        observation_ID = observation_ID,
+                        members_size = members_size,
+                        rolling = rolling,
+                        quick = quick,
+                        cores = cores)
Warning: Function compute_analogs is deprecated. Please use generateAnalogs!
Warning: rolling is not supported.
Warning: cores are automatically detected.
> which(is.na(AnEn$analogs), arr.ind = T)
     dim1 dim2 dim3 dim4 dim5
> AnEn$analogs[1, 256, 12, ,]
      [,1] [,2] [,3]
 [1,]   39    1  160
 [2,]   40    1  209
 [3,]   39    1  155
 [4,]   43    1  265
 [5,]   40    1  210
 [6,]   41    1  165
 [7,]   42    1  224
 [8,]   42    1  223
 [9,]   38    1  168
[10,]   39    1  247
[11,]   34    1  136
[12,]   39    1  171
[13,]   39    1  169
[14,]   42    1  225
[15,]   39    1  183
[16,]   43    1  203
[17,]   43    1  266
[18,]   39    1  235
[19,]   45    1  296
[20,]   39    1  167
[21,]   43    1  205
...
```

I guess this could be a version problem. What version of RAnEn are you using? I'm using `3.0.5`.

**Comment by Weiming-Hu** [comment]
You can check your library version when it is first loaded.

```
> library(RAnEn)
-------------------------------------------
-------------------------------------------
      ____   ___            ______     
     / __ \ /   |   ____   / ____/____ 
    / /_/ // /| |  / __ \ / __/  / __ \
   / _, _// ___ | / / / // /___ / / / /
  /_/ |_|/_/  |_|/_/ /_//_____//_/ /_/ 
                                       
------------------------------------------- 
-------------------------------------------
RAnEn Version 3.0.5 from GEOlab @ Penn State
Copyright (c) 2018 Weiming Hu
```

**Comment by Weiming-Hu** [comment]
Please try the version that I'm using. BTW, you can also reply here so people can see your response. Thanks.

**Comment by Weiming-Hu** [comment]
Instructions for [installations](https://weiming-hu.github.io/AnalogsEnsemble/#use-released-tarball-file)

**Comment by mcalovi** [comment]
Installed the 3.0.6 RAnEn version and now it's working, no more missing values.

**Comment by Weiming-Hu** [comment]
Hi Martina,

I've updated the website and added the fopenmp in 3.0.6. Could you please
reinstall the package and see whether it works?

Let me know if the website is more helpful now. Thanks

Weiming

On Fri, Oct 5, 2018 at 10:56 AM mcalovi <notifications@github.com> wrote:

> Installed the 3.0.6 RAnEn version and now it's working, no more missing
> values.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWeiming-Hu%2FAnalogsEnsemble%2Fissues%2F11%23issuecomment-427394197&data=02%7C01%7Cwuh20%40psu.edu%7C8efa5d633e6145705fd308d62ad2a9f9%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636743481630002961&sdata=4VaOBGmGDiDCOtwXlyzXSTvnr9rivrGhM6fhrr0szj8%3D&reserved=0>,
> or mute the thread
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPqR2oDoPBY1CYE2WJTA7ICPHp-nL1dLks5uh3L-gaJpZM4XIj6N&data=02%7C01%7Cwuh20%40psu.edu%7C8efa5d633e6145705fd308d62ad2a9f9%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636743481630012970&sdata=Qas8yNj07lhqQS2UFFfQ8ePJ4bcZeWP92dUHbmJOHJ8%3D&reserved=0>
> .
>


-- 


Weiming Hu
Geography Ph.D. Student
Geoinformatics and Earth Observation Laboratory
The Pennsylvania State University
http://geoinf.psu.edu
https://weiming.ddns.net
Email: weiming@psu.edu
Tel: 814-876-0766

("`-''-/").___..--''"`-._
 `6_ 6  )   `-.  (     ).`-.__.`)  We are.....
(_Y_.)'  ._   )  `._ `. ``-..-'     Penn State!
_..`--'_..-_/  /--'_.' ,'             Home of the
(il),-''  (li),'  ((!.-'                  Nittany Lions!
