### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Bognerk** [Weiming-Hu/AnalogsEnsemble#117]
I have just  tried to install the R package RAnEn. Unfortunately it didn't work for me. 
I have tried to install it on a Linux (Ubuntu) machine and on Windows10 (and updated beforehand R, Rtools40, RStudio).
I think the first error was the following:
In file included from /usr/lib/gcc/x86_64-pc-cygwin/10/include/c++/cctype:42,
                 from /usr/lib/gcc/x86_64-pc-cygwin/10/include/c++/bits/localefwd.h:42,
                 from /usr/lib/gcc/x86_64-pc-cygwin/10/include/c++/ios:41,
                 from /usr/lib/gcc/x86_64-pc-cygwin/10/include/c++/ostream:38,
                 from /usr/lib/gcc/x86_64-pc-cygwin/10/include/c++/iostream:39,
                 from Parameters.h:12,
                 from BasicData.h:11,
                 from Observations.h:11,
                 from AnEn.h:12,
                 from AnEn.cpp:9:
Config.h:93:25: error: expected unqualified-id before numeric constant
   93 |     static const double _X;
      |                         ^~
make: *** [/usr/lib/R/etc/Makeconf:176: AnEn.o] Error 1

**Comment by Weiming-Hu** [comment]
Thanks for using this package.

I'm a bit confused here. You said you are on a Linux machine but it seems you are using cygwin which runs on a Windows. Could you tell me a bit more about your build environment?

And also, could you let me know how you installed the package?

**Comment by Bognerk** [comment]
Sorry for the confusion! I have tried Linux, Windows10 and also R from Cygwin. I'll attach you the complete output running this command: install.packages("https://github.com/Weiming-Hu/AnalogsEnsemble/raw/master/RAnalogs/releases/RAnEn_latest.tar.gz", repos = NULL) on Windows10 from RStudio (Version 1.4.1717), R (Version R-4.1.1) and Rtool40.
[output.txt](https://github.com/Weiming-Hu/AnalogsEnsemble/files/7008888/output.txt)

**Comment by Weiming-Hu** [comment]
I assume you still have the problem but closed the issue by accident?

I have pushed a new release, 4.4.3. Please try to run the installation command again and see whether the problem persists.

**Comment by Bognerk** [comment]
Excellent!!! I have tried ton install it on both system, Linux and Windows, and it works now!!!
Thank you very much for your efforts!
