### ISSUE TITLE
Installation problem?

### ISSUE THREAD

**Issue by lovechang1986** [Weiming-Hu/AnalogsEnsemble#119]
I just only install the netcdf-c-4.8.1.
When type 'cmake -DCMAKE_INSTALL_PREFIX=~/AnalogEnsemble ..' some error occured...
```
CMake Error at /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NetCDF (missing: NETCDF_LIBRARIES NETCDF_INCLUDES
  NetCDF_has_interfaces)
Call Stack (most recent call first):
  /opt/cmake-3.12.2/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CAnEnIO/cmake/FindNetCDF.cmake:129 (find_package_handle_standard_args)
  cmake/macros.cmake:21 (_find_package)
  CAnEnIO/CMakeLists.txt:46 (find_package
```
![image](https://user-images.githubusercontent.com/8605164/153761168-99454dff-7cff-4630-9f75-32fb140c2203.png)

The question:
1. need to install the netcdf-fortran?
2. How to solve this problem?

**Comment by Weiming-Hu** [comment]
I also recommend checking out [this issue](https://github.com/Weiming-Hu/AnalogsEnsemble/issues/86#issuecomment-662576806) where it mentions how to install the C++ extension. If you are not installing to the system paths, you might also need to tell `CMake` where to find it. The issue has examples.

**Comment by Weiming-Hu** [comment]
Closing because it is related to https://github.com/Weiming-Hu/AnalogsEnsemble/issues/121
