### ISSUE TITLE
Select Analog function failed after update to 3.0.9

### ISSUE THREAD

**Issue by Weiming-Hu** [Weiming-Hu/AnalogsEnsemble#14]
Selection function failed after updating to 3.0.9. It is already known that it is due to the newly introduced parameter `extend_observations`.

**Comment by lec170** [comment]
I have the same problem

**Comment by Weiming-Hu** [comment]
Hi Laura,

This issue is resolved in the commit 2ab3d636ca2b72a2e8c9b8f1f1dc17cc5f86fdb3.

Please update your RAnEn and run the experiments again. Let me know if you encounter any problems.

**Comment by lec170** [comment]
Thank you. It is now functioning.
