### ISSUE TITLE
AnEn Selection Visualization for RAnEn Package

### ISSUE THREAD

**Issue by lec170** [Weiming-Hu/AnalogsEnsemble#15]
Created a new code for AnEn Selection visualization. Would like to add this to the RAnEn repo as a function for others to use. Can you please provide directions on how to contribute? 
[AnEn_ItalyGrid_AnalogSelection_sample_1.pdf](https://github.com/Weiming-Hu/AnalogsEnsemble/files/2673940/AnEn_ItalyGrid_AnalogSelection_sample_1.pdf)

**Comment by Weiming-Hu** [comment]
Hi Laura,

To contribute to the repo, [here](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) is a tutorial for creating a new pull request to do that. You can simply clone this repo and put the visualization script under the directory `AnalogsEnsemble/RAnalogs/RAnEn/R`. You can then create a new branch named `SSE-visualization` and push the modified repository.

Then I'll be able to see the new branch on the repo and finish the integration and make the script into a function.

Let me know if you need any help. Thank you for the contribution.

**Comment by Weiming-Hu** [comment]
Issue closed due to inactivity.
