### ISSUE TITLE
couldn't load data

### ISSUE THREAD

**Issue by yvz5525** [Weiming-Hu/AnalogsEnsemble#25]
https://hub.mybinder.org/user/weiming-hu-analogsensemble-sfodl18m/notebooks/demo-1_RAnEn-basics.ipynb

Hi,

I have problem running the code where says that " load('../analysis.RData')
load('../forecasts.RData')" The error says that there's no such file directory

**Comment by Weiming-Hu** [comment]
This has been resolved in commit a5a3d30cd042252dc1f037ff1a0fe0971658e52f. I'm closing this issue. If you still have the problem please reopen this. Thank you.
