### ISSUE TITLE
RAnEn::generateAnalogs return error messages about not matching object types

### ISSUE THREAD

**Issue by Weiming-Hu** [Weiming-Hu/AnalogsEnsemble#49]
Hi Alon, could you please upload two things here to assist the debugging?

- Run all the codes until the line that will give you the error message. Save the environment (you can remove and clear some variables that won't be used to reduce the file size. Normally it is enough that you save all the input the function that will generate the error) and try uploading it here or directly to me.
- Attach the line of code here that you didn't run and will give you the error.

Thank you

**Comment by AlonSidel** [comment]
```
library(RAnEn)
AnEn.ASOS <- ge

nerateAnalogs(config)
```

> Error in .generateAnalogs(configuration$test_forecasts, dim(configuration$test_forecasts),  : 
>   Not compatible with requested type: [type=list; target=double].

[WORKSPACE](https://psu.box.com/s/e58o9j047t84kk49xv7o7f5s5586k0su)

**Comment by Weiming-Hu** [comment]
I have just arrived in SC. I will take a look at this very soon. Sorry ......

**Comment by Weiming-Hu** [comment]
Hi Alon, looks like I can't access this file. Did you share it to the right email (wuh20@psu.edu)? Sorry for not checking this earlier....

**Comment by AlonSidel** [comment]
Can you try again with this link?
<https://psu.box.com/s/e58o9j047t84kk49xv7o7f5s5586k0su>

**Comment by Weiming-Hu** [comment]
This works. Thank you.

**Comment by Weiming-Hu** [comment]
Bug spotted. This issue reflects a fundamental problem in the checking function [RAnEn::validateConfiguration](https://github.com/Weiming-Hu/AnalogsEnsemble/blob/master/RAnalogs/RAnEn/R/validateConfiguration.R). R is apparently not a pass-by-reference language so I need to rethink how to do the checks properly and efficiently. I will update once I have made changes.

**Comment by Weiming-Hu** [comment]
Hi Alon, Please update your RAnEn to the latest version. This should be resolved.

However, you are presented with another issue.

```
> AnEn.ASOS <- generateAnalogs(config)
Convert R objects to C++ objects ...
Computing standard deviation ... 
Computing mapping from forecast [Time, FLT] to observation [Time]  ... 
Warning: Could not find some forecast times in observation times. NA values might exist.
One-on-one matching search and test stations based on indices ...
Error: Search forecasts and observations should have same numbers of stations!
Error in .generateAnalogs(configuration$test_forecasts, dim(configuration$test_forecasts),  : 
  Error code: -70
```

This is because you have more stations in the forecasts but only 1 in the observations. You need to make them consistent. Please see if this works for you.

**Comment by Weiming-Hu** [comment]
Closing issue.
