### ISSUE TITLE
RAnEn Help Documentation

### ISSUE THREAD

**Issue by lec170** [Weiming-Hu/AnalogsEnsemble#53]
Updated to the new latest version of RAnEn (using R version 6.0) and when I try to find the documentation on the RAnEn package through the normal means (?RAnEn or ??RAnEn), I receive an error. (Specifically:" Error in fetch(key) : lazy-load database '/usr/local/lib/R/3.6/site-library/RAnEn/help/RAnEn.rdb' is corrupt" prints to the screen when ?RAnEn is used and "No results found" when ??RAnEn is written.) Suggestions? Thanks!

**Comment by Weiming-Hu** [comment]
The command `??RAnEn` works for me. Could you reinstall your package and make sure it completes successfully?

**Comment by Weiming-Hu** [comment]
Closing issue.
