### ISSUE TITLE
RAnEn with different predictor weights for each point

### ISSUE THREAD

**Issue by yyang9301** [Weiming-Hu/AnalogsEnsemble#54]
The RAnEn package uses the same predictor weights for all stations/points. However, the related predictors and the corresponding weights might be dependent on locations. Is it possible to change the weight for each predictor-station combination? It seems to be easy for the independent search case (i.e., search for each location), but I don't how to deal with it with search space extension. Thank you very much in advance.

**Comment by Weiming-Hu** [comment]
It is not possible to change weights for different locations in the current implementation. The easiest way to do is probably compute each location separately with the weight combination that you want.
