### ISSUE TITLE
In need of a function that is able to call other verification function by name

### ISSUE THREAD

**Issue by Weiming-Hu** [Weiming-Hu/AnalogsEnsemble#56]
There are many verification functions. And most of the time I need to do all of them. Can I have an aggregation function that calls each of the verification function? What would the API look like?

**Comment by lec170** [comment]
We can use the Rscript I wrote to do the SSE verification. Most of it is parameterized.

**Comment by Weiming-Hu** [comment]
Could you tell me where it is? Let me try to add it to the package. Thank you.

**Comment by lec170** [comment]
Yes. Just emailed you the current version.

On Fri, Jul 26, 2019 at 4:19 PM Weiming <notifications@github.com> wrote:

> Could you tell me where it is? Let me try to add it to the package. Thank
> you.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWeiming-Hu%2FAnalogsEnsemble%2Fissues%2F56%3Femail_source%3Dnotifications%26email_token%3DADARGVHMVIUKOCNOIJKHVFLQBNL3XA5CNFSM4IHEU3L2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD25TTVQ%23issuecomment-515586518&data=02%7C01%7Clec170%40psu.edu%7C2bf0c56791464e53f30b08d7120684b9%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636997691513643630&sdata=%2BYvOQ%2F5q38a1wx95fOGuqGsfh5kdyYmG0u55lk0cQKs%3D&reserved=0>,
> or mute the thread
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADARGVEPJRL7SYX3DE47FELQBNL3XANCNFSM4IHEU3LQ&data=02%7C01%7Clec170%40psu.edu%7C2bf0c56791464e53f30b08d7120684b9%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636997691513653628&sdata=gluPAQT5I5J9tajxvfJiO2iKzJJh2lM5aKjJPUGcaqs%3D&reserved=0>
> .
>


-- 

Laura Clemente-Harding
Cell: 518-605-4505; Email: laura@psu.edu
The Pennsylvania State University
Department of Geography and Institute for CyberScience
Geoinformatics and Earth Observation Laboratory (GEOlab)
http://geoinf.psu.edu

**Comment by Weiming-Hu** [comment]
Thank you. The script looks good. I might not be able to use it as it is because it is hard to function-ize the script. But it is very helpful to guide me through the logic. Thank you.

**Comment by lec170** [comment]
Absolutely. If you want, you can also separate out the script. There are 3 parts 1) the verification stats, 2) a summary table to collect the information, and 3) plots for all the output. If you remove elements, then you can significantly decrease the information that needs to be passed down to the date, an output filename, and which verification stats you want to have completed. It might be beneficial to break it into more than one code.

**Comment by Weiming-Hu** [comment]
Thank you Laura. This issue is resolved in commit 4e641d341ef92281657a48ac811cf070164c5606. Now you can just call the `RAnEn::verify` with the desired methods and input and it will do the rest for you.
