### ISSUE TITLE
SSE generation 

### ISSUE THREAD

**Issue by lec170** [Weiming-Hu/AnalogsEnsemble#61]
Issue: I can generate SSE analogs on version 3.3.1 but I cannot generate SSE analogs on the newer version of RAnEn 3.6.0. When I try to generate the SSE analogs using the newer version of RAnEn, I receive this error message: 
Error in if (!(is.vector(x[[names.to.check[index]]], mode = "numeric") &&  : 
  missing value where TRUE/FALSE needed

I have tested this using the same Rscript on both RAnEn version builds (used 2 machines, both using OSX mojave). 

Thanks,
Laura

**Comment by Weiming-Hu** [comment]
This has been resolved in dc9322b
