### ISSUE TITLE
gribConverter Error During Install on Linux

### ISSUE THREAD

**Issue by map579** [Weiming-Hu/AnalogsEnsemble#73]
While following the directions to install gribConverter on Ubuntu (18.04.3) in an Oracle VM VirtualBox, I received an error stating that it "Could NOT find NetCDF (missing:  NETCDF_LIBRARIES NETCDF_INCLUDES)".  

To get this bug, I followed the instructions of changing the directory to AnalogsEnsemble/build and ran "cmake -DUBILD_GRIBCONVERTER=ON .."  The attached image shows this error I received:

![2020-02-01 07_53_24-UIMachineViewNormalClassWindow](https://user-images.githubusercontent.com/43961060/73592402-09fdd700-44c8-11ea-84cc-e99eee2f7f85.jpg)

map@map-VirtualBox:~/AnalogsEnsemble/build$ cmake -DBUILD_GRIBCONVERTER=ON ..
You are building version 3.7.1
-- CMAKE_INSTALL_RPATH:
/home/map/AnalogsEnsemble/dependency/install/lib/;/home/map/AnalogsEnse
mble/output/lib
-- Remove system root when GNU is used.
-- CMAKE_BUILD_TYPE is Release
-- C++ compiler options are: -O3 -DNDEBUG -s -w
-- Found OpenMP_C: -fopenmp 
-- Found OpenMP_CXX: -fopenmp 
-- Found OpenMP: TRUE   
-- Using OpenMP -fopenmp
-- Could NOT find NetCDF (missing: NETCDF_LIBRARIES NETCDF_INCLUDES)
-- netCDF is not found or does not meet the requirement. Try to build
it.
-- Or please specify the variable CMAKE_PREFIX_PATH which contains
/bin, /lib, and /include.
CMake Error at /usr/share/cmake-
3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378
(_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindCURL.cmake:48
(FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists_netCDF.txt:74 (find_package)
  CMakeLists.txt:171 (include)

**Comment by Weiming-Hu** [comment]
Hi Mark,

Looks like the cmake is trying to build netcdf but fail to find it's
requirement. I would suggest you just install netcdf with apt get install
and try again.

**Comment by Weiming-Hu** [comment]
After the dependencies (NetCDF, gFortran from eccodes) are installed, issues were resolved. Closing.
